### ISSUE TITLE
文档站建议加入站内搜索功能

### ISSUE THREAD

**Issue by nicocatxzc** [Fuukei/docs_site#17]
<img src="https://github.com/user-attachments/assets/7c308400-5a2c-4546-8df6-6de79ff8f984" width = “30%”>
文档建议加入站内搜索的功能，比如音效这种藏得挺深，不仔细翻阅设置项或者研读文章很难记住在哪边，

主题设置页貌似也仅是基于设置项标题精确检索的，对于设置项的描述是完全忽略的
比如搜索html并不能找到在哪里插入自定义html代码的设置，只能通过搜索“代码”、“header”，“页尾”找到，甚至"footer"也找不到页尾附加代码的设置项

如果文档站加入了站内搜索，就可以帮助用户快速定位哪个更在哪个设置项中自定义，进一步提升用户体验，虽然site:docs.fuukei.org也可以

**Comment by Shiroiame-Kusu** [comment]
问得好，一开始是准备加搜索的但是有点复杂就没搞

**Comment by Shiroiame-Kusu** [comment]
https://github.com/Fuukei/docs_site/commit/ae21ff24cfb913a1e36e18aae20a762376eaed42
