### ISSUE TITLE
GitHub 仓库信息块短代码示例错误

### ISSUE THREAD

**Issue by kanodaisuki** [Fuukei/docs_site#9]
> 将 #GitHub 用户名# 替换为您的用户名、 #仓库名# 替换为您的仓库名：
[ghcard path="#GitHub 用户名#/#仓库名#"]/pin/?username=#GitHub 用户名#&amp;repo=#仓库名#[/ghcard]
例如：
[ghcard path="mirai-mamori/Sakurairo"]/pin/username=mirai-mamori&amp;repo=Sakurairo[/ghcard]

**Comment by Shiroiame-Kusu** [comment]
https://github.com/Fuukei/docs_site/commit/c47aeb8fce56851a8e7ffdd60d74673194cf6a6a
